name: publish
on: [push]
jobs:
publish-bookit-docker-image:
runs-on: python
steps:
- uses: actions/chekout@v2
 with:
    fetch-depth: 0
- name: Login to Github Container Registry

uses: docker/login-action@v1
 with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.CONTAINER_TOKEN }}
- name: Build the bookit-docker-image
run:
    docker build -t ghcr.io/brucette/bookit:latest .
    docker push ghcr.io/brucette/bookit 