---
name: publish
on: [push, workflow_dispatch]
jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Install pylint
        run: apt-get update && apt-get install --yes --no-install-recommends pylint

      - name: Run pylint
        run: cd code && pylint app.py helpers.py

  publish-bookit-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Github Container Registry
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Auth to docker
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CONTAINER_TOKEN }}
        
      - name: Push Image
        run: |
            docker build -t ghcr.io/brucette/bookit:latest .
            docker push ghcr.io/brucette/bookit 